# Preparations

In [50]:
# #Use when accidently run Preparations again
# import gc

# # Delete existing large objects
# if 'train_disruption' in locals():
#     del train_disruption

# # Force garbage collection
# gc.collect()

## Load Packages and Libraries

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import StandardScaler
import csv 
import os

## Load Dataset
In batches:
- services 2019-2022
- services 2023-2025
- disruptions 2019-2022
- disruptions 2023-2025
- weather 2019-2025

In [2]:
#Load in dataset services 2019-2022 (0.1s)
serv19 = pd.read_csv("Train Disruptions 2019-2025/disruptions-2019.csv")
serv20 = pd.read_csv("Train Disruptions 2019-2025/disruptions-2020.csv")
serv21 = pd.read_csv("Train Disruptions 2019-2025/disruptions-2021.csv")
serv22 = pd.read_csv("Train Disruptions 2019-2025/disruptions-2022.csv")

In [3]:
#Load in dataset services 2023-2025 (0.0s)
serv23 = pd.read_csv("Train Disruptions 2019-2025/disruptions-2023.csv")
serv24 = pd.read_csv("Train Disruptions 2019-2025/disruptions-2024.csv")
serv25 = pd.read_csv("Train Disruptions 2019-2025/disruptions-2025.csv")

In [4]:
#Load in dataset disruptions 2019-2022 (3m8s)
dis19 = pd.read_csv("Train Services 2019-2025/services-2019.csv")
dis20 = pd.read_csv("Train Services 2019-2025/services-2020.csv")
dis21 = pd.read_csv("Train Services 2019-2025/services-2021.csv")
dis22 = pd.read_csv("Train Services 2019-2025/services-2022.csv")

In [5]:
#Load in dataset disruptions 2023-2025 (2m54ss)
dis23 = pd.read_csv("Train Services 2019-2025/services-2023.csv")
dis24 = pd.read_csv("Train Services 2019-2025/services-2024.csv")
dis25 = pd.read_csv("Train Services 2019-2025/services-2025.csv")

In [6]:
#Load in dataset weather 2019-2025 (0.0s)
weather = pd.read_csv( "Weather 2019-2025/Weather 2019-2025.txt", sep= ',', skiprows= 46, header= 0 )

## Concatenate Dataset: Services

In [7]:
#Concatenate dataset services as one (0.1s)

train_services = pd.concat([serv19, serv20, serv21, serv22, serv23, serv24, serv25], ignore_index= True)
serv_col_names = train_services.columns
print( f" The column names of services are: {serv_col_names}" )

rows, columns = train_services.shape
print( f"train_services has Rows: {rows}, Columns: {columns}" ) #Rows: 38571, Columns: 14

 The column names of services are: Index(['rdt_id', 'ns_lines', 'rdt_lines', 'rdt_lines_id', 'rdt_station_names',
       'rdt_station_codes', 'cause_nl', 'cause_en', 'statistical_cause_nl',
       'statistical_cause_en', 'cause_group', 'start_time', 'end_time',
       'duration_minutes'],
      dtype='str')
train_services has Rows: 38571, Columns: 14

In [58]:
# #Run when trying to run train_disruption again
# import gc

# # Delete existing large objects
# if 'train_disruption' in locals(): #change 'train_disruption' if you want to track something else
#     del train_disruption

# # Force garbage collection
# gc.collect()

## Concatenate Dataset: Disruptions

In [8]:
#Concatenate dataset disruption as one (2m45s)

train_disruption = pd.concat([dis19, dis20, dis21, dis22, dis23, dis24, dis25], ignore_index= True)
col_names = train_disruption.columns
print( f" The column names of disruptions are: {col_names}" )

rows, columns = train_disruption.shape
print( f"train_disruption has Rows: {rows}, Columns: {columns}")

 The column names of disruptions are: Index(['Service:RDT-ID', 'Service:Date', 'Service:Type', 'Service:Company',
       'Service:Train number', 'Service:Completely cancelled',
       'Service:Partly cancelled', 'Service:Maximum delay', 'Stop:RDT-ID',
       'Stop:Station code', 'Stop:Station name', 'Stop:Arrival time',
       'Stop:Arrival delay', 'Stop:Arrival cancelled', 'Stop:Departure time',
       'Stop:Departure delay', 'Stop:Departure cancelled',
       'Stop:Platform change', 'Stop:Planned platform',
       'Stop:Actual platform'],
      dtype='str')
train_disruption has Rows: 152176324, Columns: 20

## Data Preparation: Weather

In [9]:
#Check dataset weather as one (0.0s)

weather_col_names = weather.columns
print( f" The column names of weather are: {weather_col_names}" )

rows, columns = weather.shape
print( f"Dataset weather has Rows: {rows}, Columns: {columns}")

 The column names of weather are: Index(['# STN', 'YYYYMMDD', 'DDVEC', 'FHVEC', '   FG', '  FHX', ' FHXH',
       '  FHN', ' FHNH', '  FXX', ' FXXH', '   TG', '   TN', '  TNH', '   TX',
       '  TXH', ' T10N', 'T10NH', '   SQ', '   SP', '    Q', '   DR', '   RH',
       '  RHX', ' RHXH', '   PG', '   PX', '  PXH', '   PN', '  PNH', '  VVN',
       ' VVNH', '  VVX', ' VVXH', '   NG', '   UG', '   UX', '  UXH', '   UN',
       '  UNH', ' EV24'],
      dtype='str')
Dataset weather has Rows: 2557, Columns: 41

# Exploratory Data Analysis

Created dataframes:
- weather
- train_disruption
- train_services

## EDA: train_services

In [10]:
#Analyzing train_services
print(train_services.info())

<class 'pandas.DataFrame'>
RangeIndex: 38571 entries, 0 to 38570
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   rdt_id                38571 non-null  int64
 1   ns_lines              38571 non-null  str
 2   rdt_lines             38559 non-null  str
 3   rdt_lines_id          38559 non-null  str
 4   rdt_station_names     38563 non-null  str
 5   rdt_station_codes     38563 non-null  str
 6   cause_nl              38571 non-null  str
 7   cause_en              38571 non-null  str
 8   statistical_cause_nl  38571 non-null  str
 9   statistical_cause_en  38571 non-null  str
 10  cause_group           38569 non-null  str
 11  start_time            38571 non-null  str
 12  end_time              38461 non-null  str
 13  duration_minutes      38460 non-null  float64
dtypes: float64(1), int64(1), str(12)
memory usage: 4.1 MB
None

In [11]:
#Analyzing train_services
train_services.describe().T

,count,mean,std,min,25%,50%,75%,max
rdt_id,38571.0,44571.139224,11193.096194,25236.0,34878.5,44521.0,54316.5,63959.0
duration_minutes,38460.0,162.620281,859.044243,0.0,18.0,47.0,131.0,45302.0

In [12]:
#check for Missing Value 
#code from 12:59 https://www.youtube.com/watch?v=MoM6mighOJM&t=778s 

total_serv = train_services.isnull().sum().sort_values(ascending=False)
percent_serv = (train_services.isnull().sum()/train_services.isnull().count().sort_values(ascending=False))
missvalue_services = pd.concat([total_serv,percent_serv], axis= 1, keys=["Total", "Percent"])
missvalue_services

                      Total   Percent
duration_minutes        111  0.002878
end_time                110  0.002852
rdt_lines_id             12  0.000311
rdt_lines                12  0.000311
rdt_station_names         8  0.000207
rdt_station_codes         8  0.000207
cause_group               2  0.000052
ns_lines                  0  0.000000
rdt_id                    0  0.000000
cause_nl                  0  0.000000
statistical_cause_en      0  0.000000
statistical_cause_nl      0  0.000000
cause_en                  0  0.000000
start_time                0  0.000000

In [13]:
#Check for any duplicates in the dataset
train_services.duplicated().sum()

np.int64(0)

In [14]:
#Removing the rows with missing values
serv_cleaned = train_services.dropna()

print("Dataset services after removing rows with missing values:")
print(serv_cleaned)

#Old [38571 rows x 14 columns]
#New [38446 rows x 14 columns]
#removed 125 rows

Dataset services after removing rows with missing values:
       rdt_id                                           ns_lines  \
0       25236                           Utrecht-'s-Hertogenbosch
1       25237  Almere-Lelystad; Almere-Lelystad; Hoofddorp-Sc...
2       25238                                  Amersfoort-Zwolle
3       25239             Utrecht-'s-Hertogenbosch; Utrecht-Tiel
4       25240                                  Amersfoort-Zwolle
...       ...                                                ...
38566   63955                                Almelo - Hardenberg
38567   63956                                   Schiphol Airport
38568   63957                                Almelo - Hardenberg
38569   63958                  Hilversum - Amersfoort Schothorst
38570   63959                                            Alkmaar

                                               rdt_lines  \
0                    's-Hertogenbosch - Utrecht Centraal
1      Almere Oostvaarders - Utrecht Centraal, Amster...
2                                    Amersfoort - Zwolle
3      's-Hertogenbosch - Utrecht Centraal, Tiel - Ut...
4                                    Amersfoort - Zwolle
...                                                  ...
38566                                Almelo - Mariënberg
38567  Amersfoort - Schiphol Airport, Amsterdam Centr...
38568                                Almelo - Mariënberg
38569                                Amersfoort - Zwolle
38570  Alkmaar - Amsterdam Centraal, Alkmaar - Den He...

                   rdt_lines_id  \
0                           151
1                   144,145,149
2                            48
3                       150,151
4                            48
...                         ...
38566                        96
38567  22,24,32,137,144,148,165
38568                        96
38569                        48
38570               161,162,163

                                       rdt_station_names  \
0               Geldermalsen,'s-Hertogenbosch,Zaltbommel
1                   Almere Oostvaarders,Lelystad Centrum
2                               Ermelo,Harderwijk,Putten
3                Culemborg,Geldermalsen,Houten Castellum
4      Amersfoort Centraal,Amersfoort Schothorst,Amer...
...                                                  ...
38566  Almelo,Daarlerveen,Mariënberg,Vroomshoop,Vriez...
38567                          Rosmalen,Schiphol Airport
38568  Almelo,Daarlerveen,Mariënberg,Vroomshoop,Vriez...
38569          Amersfoort Centraal,Amersfoort Schothorst
38570                          Alkmaar,Oisterwijk,Dülken

                                       rdt_station_codes  \
0                                           GDM, HT, ZBM
1                                              ALMO, LLS
2                                            EML, HD, PT
3                                          CL, GDM, HTNC
4      AMF, AMFS, AVAT, EML, HD, HDE, NKK, NS, PT, WZ...
...                                                  ...
38566                              AML, DA, MRB, VHP, VZ
38567                                            RS, SHL
38568                              AML, DA, MRB, VHP, VZ
38569                                          AMF, AMFS
38570                                      AMR, OT, KDUL

                     cause_nl                cause_en    statistical_cause_nl  \
0        defecte bovenleiding  damaged overhead wires    defecte bovenleiding
1                  vandalisme               vandalism              vandalisme
2                 seinstoring          signal failure             seinstoring
3      inzet van hulpdiensten       an emergency call  inzet van hulpdiensten
4        herstelwerkzaamheden            repair works    herstelwerkzaamheden
...                       ...                     ...                     ...
38566              vandalisme               vandalism              vandalisme
38567            brandmelding              fire alarm            brandmelding
38568              vandalisme               vandalism              vandalisme
38569           defecte trein       broken down train           defecte trein
38570              aanrijding               collision              aanrijding

         statistical_cause_en       cause_group           start_time  \
0      damaged overhead wires    infrastructure  2019-01-01 06:32:16
1                   vandalism          external  2019-01-01 07:12:00
2              signal failure    infrastructure  2019-01-01 08:26:58
3           an emergency call          external  2019-01-01 08:36:00
4                repair works  engineering work  2019-01-01 09:45:48
...                       ...               ...                  ...
38566               vandalism          external  2025-12-31 15:14:17
38567              fire alarm          external  2025-12-31 16:19:41
38568               vandalism          external  2025-12-31 16:31:29
38569       broken down train     rolling stock  2025-12-31 18:48:51
38570               collision         accidents  2025-12-31 19:41:03

                  end_time  duration_minutes
0      2019-01-01 06:33:31               1.0
1      2019-01-01 09:53:48             162.0
2      2019-01-01 08:44:01              17.0
3      2019-01-01 09:09:43              34.0
4      2019-01-01 12:47:54             182.0
...                    ...               ...
38566  2025-12-31 15:48:40              34.0
38567  2025-12-31 17:00:26              41.0
38568  2025-12-31 21:15:20             284.0
38569  2025-12-31 19:40:04              51.0
38570  2025-12-31 19:46:40               6.0

[38446 rows x 14 columns]

In [ ]:
#Univariate Analysis
#right-skewed with extreme outliers

# Check for outliers 
print(train_services['duration_minutes'].describe())
print(f"\n99th percentile: {train_services['duration_minutes'].quantile(0.99):.0f} minutes")
print(f"Max: {train_services['duration_minutes'].max():.0f} minutes")

for p in [90, 95, 99, 99.9]:
    value = train_services['duration_minutes'].quantile(p/100)
    count = (train_services['duration_minutes'] > value).sum()
    print(f"Top {100-p}% (> {value:.0f} min): {count} disruptions")

count    38460.000000
mean       162.620281
std        859.044243
min          0.000000
25%         18.000000
50%         47.000000
75%        131.000000
max      45302.000000
Name: duration_minutes, dtype: float64

99th percentile: 1438 minutes
Max: 45302 minutes
Top 10% (> 272 min): 3842 disruptions
Top 5% (> 516 min): 1921 disruptions
Top 1% (> 1438 min): 385 disruptions
Top 0.09999999999999432% (> 11000 min): 39 disruptions

In [ ]:
log_duration = np.log1p(train_services["duration_minutes"])

count    38460.000000
mean       162.620281
std        859.044243
min          0.000000
25%         18.000000
50%         47.000000
75%        131.000000
max      45302.000000
Name: duration_minutes, dtype: float64

99th percentile: 1438 minutes
Max: 45302 minutes
Top 10% (> 272 min): 3842 disruptions
Top 5% (> 516 min): 1921 disruptions
Top 1% (> 1438 min): 385 disruptions
Top 0.09999999999999432% (> 11000 min): 39 disruptions

## EDA: train_disruption

In [17]:
#Analyzing train_disruption
print(train_disruption.info())

<class 'pandas.DataFrame'>
Index: 152176324 entries, 0 to 22226310
Data columns (total 20 columns):
 #   Column                        Dtype
---  ------                        -----
 0   Service:RDT-ID                int64
 1   Service:Date                  str
 2   Service:Type                  str
 3   Service:Company               str
 4   Service:Train number          int64
 5   Service:Completely cancelled  bool
 6   Service:Partly cancelled      bool
 7   Service:Maximum delay         int64
 8   Stop:RDT-ID                   int64
 9   Stop:Station code             str
 10  Stop:Station name             str
 11  Stop:Arrival time             str
 12  Stop:Arrival delay            float64
 13  Stop:Arrival cancelled        object
 14  Stop:Departure time           str
 15  Stop:Departure delay          float64
 16  Stop:Departure cancelled      object
 17  Stop:Platform change          bool
 18  Stop:Planned platform         str
 19  Stop:Actual platform          str
dtypes: bool(3), float64(2), int64(4), object(2), str(9)
memory usage: 20.8+ GB
None

In [ ]:
#describe train_disruption (53.3s)
train_disruption.describe().T

,count,mean,std,min,25%,50%,75%,max
Service:RDT-ID,152176324.0,9.165301e+06,4.826652e+06,738804.0,5016868.00,9137173.0,1.334079e+07,17504617.0
Service:Train number,152176324.0,5.682374e+04,1.908578e+05,1.0,4092.00,6922.0,2.031300e+04,90202042.0
Service:Maximum delay,152176324.0,1.941803e-01,1.559290e+00,-74.0,0.00,0.0,0.000000e+00,1500.0
Stop:RDT-ID,152176324.0,8.230830e+07,4.392954e+07,6220112.0,44264202.75,82308283.5,1.203524e+08,158545506.0
Stop:Arrival delay,135255061.0,7.261503e-01,3.110886e+00,-92.0,0.00,0.0,0.000000e+00,1499.0
Stop:Departure delay,135523200.0,7.252628e-01,2.937628e+00,-1351.0,0.00,0.0,1.000000e+00,1500.0

## EDA: weather

In [19]:
print(weather.info())

<class 'pandas.DataFrame'>
RangeIndex: 2557 entries, 0 to 2556
Data columns (total 41 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   # STN     2557 non-null   int64
 1   YYYYMMDD  2557 non-null   int64
 2   DDVEC     2557 non-null   int64
 3   FHVEC     2557 non-null   int64
 4      FG     2557 non-null   int64
 5     FHX     2557 non-null   int64
 6    FHXH     2557 non-null   int64
 7     FHN     2557 non-null   int64
 8    FHNH     2557 non-null   int64
 9     FXX     2557 non-null   int64
 10   FXXH     2557 non-null   int64
 11     TG     2557 non-null   int64
 12     TN     2557 non-null   int64
 13    TNH     2557 non-null   int64
 14     TX     2557 non-null   int64
 15    TXH     2557 non-null   int64
 16   T10N     2557 non-null   int64
 17  T10NH     2557 non-null   int64
 18     SQ     2557 non-null   int64
 19     SP     2557 non-null   int64
 20      Q     2557 non-null   int64
 21     DR     2557 non-null   int64
 22     RH     2557 non-null   int64
 23    RHX     2557 non-null   int64
 24   RHXH     2557 non-null   int64
 25     PG     2557 non-null   int64
 26     PX     2557 non-null   int64
 27    PXH     2557 non-null   int64
 28     PN     2557 non-null   int64
 29    PNH     2557 non-null   int64
 30    VVN     2557 non-null   int64
 31   VVNH     2557 non-null   int64
 32    VVX     2557 non-null   int64
 33   VVXH     2557 non-null   int64
 34     NG     2557 non-null   str
 35     UG     2557 non-null   int64
 36     UX     2557 non-null   int64
 37    UXH     2557 non-null   int64
 38     UN     2557 non-null   int64
 39    UNH     2557 non-null   int64
 40   EV24     2557 non-null   int64
dtypes: int64(40), str(1)
memory usage: 819.2 KB
None

In [22]:
weather.describe().T

,count,mean,std,min,25%,50%,75%,max
# STN,2557.0,2.600000e+02,0.000000,260.0,260.0,260.0,260.0,260.0
YYYYMMDD,2557.0,2.022067e+07,20006.889442,20190101.0,20201001.0,20220702.0,20240401.0,20251231.0
DDVEC,2557.0,1.908084e+02,90.926323,1.0,131.0,206.0,250.0,360.0
FHVEC,2557.0,2.927141e+01,14.995639,0.0,18.0,27.0,38.0,94.0
FG,2557.0,3.336918e+01,13.845270,7.0,23.0,31.0,41.0,98.0
FHX,2557.0,5.128666e+01,18.055588,20.0,40.0,50.0,60.0,150.0
FHXH,2557.0,1.091044e+01,5.397954,1.0,8.0,11.0,14.0,24.0
FHN,2557.0,1.610481e+01,11.798449,0.0,10.0,10.0,20.0,70.0
FHNH,2557.0,8.427063e+00,8.547612,1.0,1.0,4.0,18.0,24.0
FXX,2557.0,1.026555e+02,37.214587,30.0,80.0,100.0,120.0,310.0
FXXH,2557.0,1.225772e+01,5.331835,1.0,10.0,13.0,15.0,24.0
TG,2557.0,1.141998e+02,59.374079,-58.0,70.0,112.0,162.0,288.0
TN,2557.0,6.947321e+01,54.153637,-109.0,30.0,71.0,111.0,223.0
TNH,2557.0,1.115604e+01,9.411659,1.0,4.0,6.0,23.0,24.0
TX,2557.0,1.550993e+02,69.864761,-48.0,102.0,153.0,209.0,375.0
TXH,2557.0,1.374501e+01,3.804070,1.0,13.0,14.0,15.0,24.0
T10N,2557.0,5.117638e+01,56.338471,-135.0,12.0,54.0,92.0,214.0
T10NH,2557.0,1.340321e+01,8.521842,6.0,6.0,6.0,24.0,24.0
SQ,2557.0,5.283496e+01,43.932746,0.0,12.0,46.0,87.0,155.0
SP,2557.0,4.038756e+01,31.037870,0.0,11.0,37.0,67.0,94.0
Q,2557.0,1.097985e+03,833.288930,31.0,342.0,946.0,1757.0,3109.0
DR,2557.0,1.798749e+01,29.936223,0.0,0.0,2.0,25.0,196.0
RH,2557.0,2.484357e+01,49.397455,-1.0,0.0,1.0,28.0,533.0
RHX,2557.0,9.594447e+00,20.062777,-1.0,0.0,1.0,12.0,326.0
RHXH,2557.0,6.814627e+00,7.696008,1.0,1.0,1.0,13.0,24.0
PG,2557.0,1.015289e+04,103.133619,9750.0,10089.0,10159.0,10222.0,10467.0
PX,2557.0,1.018396e+04,96.433723,9796.0,10124.0,10188.0,10248.0,10481.0
PXH,2557.0,1.236645e+01,9.644374,1.0,1.0,10.0,23.0,24.0
PN,2557.0,1.012044e+04,111.480117,9695.0,10054.0,10129.0,10196.0,10446.0
PNH,2557.0,1.218772e+01,9.533810,1.0,2.0,14.0,24.0,24.0
VVN,2557.0,3.972976e+01,24.693507,0.0,15.0,49.0,61.0,82.0
VVNH,2557.0,9.897927e+00,8.519387,1.0,3.0,6.0,19.0,24.0
VVX,2557.0,7.802073e+01,7.072227,15.0,75.0,81.0,83.0,83.0
VVXH,2557.0,1.209894e+01,5.741769,1.0,10.0,13.0,16.0,24.0
UG,2557.0,7.902112e+01,10.765404,37.0,73.0,80.0,87.0,100.0
UX,2557.0,9.467697e+01,5.835016,52.0,93.0,97.0,98.0,100.0
UXH,2557.0,9.556903e+00,8.899565,1.0,2.0,5.0,20.0,24.0
UN,2557.0,6.120336e+01,16.182888,16.0,49.0,61.0,74.0,98.0
UNH,2557.0,1.344857e+01,4.024110,1.0,12.0,14.0,15.0,24.0
EV24,2557.0,1.773250e+01,14.754101,0.0,5.0,14.0,28.0,59.0